/**
 * JEXI OS — Phase 23 Scope B — forgejo-mcp pull-request tools (20).
 *
 * Data-only module; see repo-tools.js for the entry shape. Tool surface
 * follows the Forgejo/Gitea pull-request API: lifecycle, merging, diffs,
 * reviews, reviewers, branch updates, CI status.
 */

export const PR_TOOLS = [
  { short: 'list', description: 'List pull requests of a repository, filterable by state.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['state', false, 'string', 'open, closed or all; defaults to open'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'get', description: 'Get a pull request by index, including its mergeability.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index']] },
  { short: 'create', description: 'Open a pull request from head to base.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['title', true, 'string', 'Pull request title'], ['head', true, 'string', 'Source branch'], ['base', true, 'string', 'Target branch'], ['body', false, 'string', 'Description body (markdown)']] },
  { short: 'edit', description: "Edit a pull request's title or body.", params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index'], ['title', false, 'string', 'New title'], ['body', false, 'string', 'New body']] },
  { short: 'close', description: 'Close a pull request without merging.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index']] },
  { short: 'reopen', description: 'Reopen a closed, unmerged pull request.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index']] },
  { short: 'merge', description: 'Merge a pull request.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index'], ['method', false, 'string', 'merge, rebase, rebase-merge or squash; uses the repository default when omitted'], ['title', false, 'string', 'Title of the merge commit'], ['message', false, 'string', 'Body of the merge commit']] },
  { short: 'merge-check', description: 'Check whether a pull request is currently mergeable and why not.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index']] },
  { short: 'list-files', description: 'List the files changed by a pull request.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'get-diff', description: 'Get the raw diff of a pull request.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index']] },
  { short: 'list-commits', description: 'List the commits contained in a pull request.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'list-comments', description: 'List comments on a pull request.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'add-comment', description: 'Comment on a pull request.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index'], ['body', true, 'string', 'Comment body (markdown)']] },
  { short: 'list-reviews', description: 'List reviews submitted on a pull request.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'create-review', description: 'Submit a review on a pull request.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index'], ['event', true, 'string', 'APPROVED, REQUEST_CHANGES or COMMENT'], ['body', false, 'string', 'Review body (required for REQUEST_CHANGES and COMMENT)']] },
  { short: 'dismiss-review', description: 'Dismiss a previously submitted review.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index'], ['id', true, 'number', 'Review id to dismiss']] },
  { short: 'list-reviewers', description: 'List the reviewers requested on a pull request.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index']] },
  { short: 'request-review', description: 'Request a review from a set of users.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index'], ['reviewers', true, 'array', 'Usernames to request reviews from']] },
  { short: 'update-branch', description: 'Update the head branch of a pull request from its base branch.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index']] },
  { short: 'get-status', description: "Get the combined CI status of a pull request's head ref.", params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['index', true, 'number', 'Pull request index']] },
];
