/**
 * JEXI OS — Phase 23 Scope B — forgejo-mcp repo tools (33).
 *
 * Data-only module: one entry per tool, shaped
 *   { short, description, params: [ [name, required, type, description?] ] }
 * taxonomy.js owns normalization (short -> 'repo.<short>', tuples -> param
 * objects) so this file stays free of imports and evaluation-order hazards.
 *
 * Tool surface follows the Forgejo/Gitea repository API: repositories,
 * branches, tags, commits, contents, releases, webhooks, collaborators.
 */

export const REPO_TOOLS = [
  { short: 'list', description: 'List repositories accessible to the authenticated account, most recently updated first.', params: [['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size (server cap applies)']] },
  { short: 'search', description: 'Search repositories by keyword across names, descriptions and topics.', params: [['q', true, 'string', 'Search keyword'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'get', description: 'Get a repository by owner and name, including its metadata and permissions of the caller.', params: [['owner', true, 'string', 'Repository owner (user or org)'], ['repo', true, 'string', 'Repository name']] },
  { short: 'create', description: 'Create a new repository owned by the authenticated user.', params: [['name', true, 'string', 'Repository name'], ['description', false, 'string', 'Repository description'], ['private', false, 'boolean', 'Create as a private repository'], ['autoInit', false, 'boolean', 'Initialize the repository with a README']] },
  { short: 'edit', description: 'Edit repository properties such as description, visibility and default branch.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['description', false, 'string', 'New description'], ['private', false, 'boolean', 'Change visibility'], ['defaultBranch', false, 'string', 'New default branch name']] },
  { short: 'delete', description: 'Delete a repository. Irreversible: branches, issues and releases go with it.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name']] },
  { short: 'fork', description: 'Fork a repository into the authenticated account or a named organization.', params: [['owner', true, 'string', 'Source repository owner'], ['repo', true, 'string', 'Source repository name'], ['organization', false, 'string', 'Target organization; defaults to the authenticated user']] },
  { short: 'list-branches', description: 'List branches of a repository.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'get-branch', description: 'Get a single branch, including the commit status of its head.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['branch', true, 'string', 'Branch name']] },
  { short: 'create-branch', description: 'Create a branch pointing at an existing ref.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['branch', true, 'string', 'New branch name'], ['ref', false, 'string', 'Source ref; defaults to the repository default branch']] },
  { short: 'delete-branch', description: 'Delete a branch. The default branch cannot be deleted.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['branch', true, 'string', 'Branch name']] },
  { short: 'list-tags', description: 'List tags of a repository.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'create-tag', description: 'Create a tag, optionally pointing at a target commit instead of the default branch head.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['tag', true, 'string', 'Tag name'], ['target', false, 'string', 'Commit SHA or ref to tag']] },
  { short: 'delete-tag', description: 'Delete a tag.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['tag', true, 'string', 'Tag name']] },
  { short: 'list-commits', description: 'List commits, optionally narrowed to a ref or a file path.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['sha', false, 'string', 'Branch, tag or SHA to list from'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'get-commit', description: 'Get a single commit with its full diff.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['sha', true, 'string', 'Commit SHA']] },
  { short: 'compare', description: 'Compare two refs and return the commits and changed files between them.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['base', true, 'string', 'Base ref'], ['head', true, 'string', 'Head ref']] },
  { short: 'get-file', description: 'Get the contents and metadata of a file at a ref.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['filepath', true, 'string', 'Path of the file'], ['ref', false, 'string', 'Branch, tag or SHA; defaults to the default branch']] },
  { short: 'list-contents', description: 'List the entries of a directory at a ref.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['filepath', false, 'string', 'Directory path; defaults to the repository root'], ['ref', false, 'string', 'Branch, tag or SHA']] },
  { short: 'create-file', description: 'Create a file in a repository via a commit.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['filepath', true, 'string', 'Path of the file to create'], ['content', true, 'string', 'File content (Forgejo API encoding)'], ['message', true, 'string', 'Commit message'], ['branch', false, 'string', 'Target branch; defaults to the default branch']] },
  { short: 'update-file', description: 'Update an existing file via a commit.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['filepath', true, 'string', 'Path of the file to update'], ['content', true, 'string', 'New file content (Forgejo API encoding)'], ['message', true, 'string', 'Commit message'], ['sha', true, 'string', 'Blob SHA of the file being replaced'], ['branch', false, 'string', 'Target branch']] },
  { short: 'delete-file', description: 'Delete a file via a commit.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['filepath', true, 'string', 'Path of the file to delete'], ['message', true, 'string', 'Commit message'], ['sha', true, 'string', 'Blob SHA of the file being deleted'], ['branch', false, 'string', 'Target branch']] },
  { short: 'list-releases', description: 'List releases of a repository.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'get-release', description: 'Get a release by id.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['id', true, 'number', 'Release id']] },
  { short: 'create-release', description: 'Create a release for an existing tag.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['tagName', true, 'string', 'Existing tag to release'], ['name', false, 'string', 'Release title'], ['body', false, 'string', 'Release notes body']] },
  { short: 'delete-release', description: 'Delete a release by id. The underlying tag is untouched.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['id', true, 'number', 'Release id']] },
  { short: 'list-webhooks', description: 'List webhooks configured on a repository.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'create-webhook', description: 'Create a webhook on a repository.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['url', true, 'string', 'Payload target URL'], ['events', true, 'array', 'Event names that trigger the webhook'], ['type', false, 'string', 'Payload content type; defaults to json']] },
  { short: 'delete-webhook', description: 'Delete a repository webhook by id.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['id', true, 'number', 'Webhook id']] },
  { short: 'list-collaborators', description: 'List collaborators of a repository and their permission level.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['page', false, 'number', '1-based page number'], ['limit', false, 'number', 'Page size']] },
  { short: 'add-collaborator', description: 'Grant a user access to a repository at a permission level.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['collaborator', true, 'string', 'User to add'], ['permission', false, 'string', 'read, write or admin; defaults to write']] },
  { short: 'remove-collaborator', description: 'Revoke a user access to a repository.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['collaborator', true, 'string', 'User to remove']] },
  { short: 'get-archive', description: 'Download a repository archive (tarball or zipball) at a ref.', params: [['owner', true, 'string', 'Repository owner'], ['repo', true, 'string', 'Repository name'], ['format', true, 'string', 'tar.gz or zip'], ['ref', false, 'string', 'Branch, tag or SHA; defaults to the default branch']] },
];
