import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn, spawnSync, execFileSync } from 'node:child_process';
import { once } from 'node:events';
import { createState } from '../harness/state/index.js';
import { createRefine } from '../harness/refine/index.js';
import { apply } from '../harness/refine/applier.js';
import { canonical } from '../harness/state/journal.js';
import command from '../commands/refine.command.js';
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'phase10-c-'));
const cwd = process.cwd();
let child;
let passed = 0;
const pass = name => { passed++; console.log(`PASS ${name}`); };
function trajectory(id, events) { const file = path.join(root, `${id}.json`); fs.writeFileSync(file, JSON.stringify({ id, events })); return file; }
const correction = { kind: 'user_correction', detail: 'preferred JSON over YAML', at: '2026-09-20T09:00:00Z' };
const file = trajectory('format', [correction]);
const originalTrajectory = fs.readFileSync(file);
const state = createState({ directory: path.join(root, 'state') });
const directory = path.join(root, 'snapshots');
const refine = createRefine({ state, directory });
const bytes = () => Buffer.from(JSON.stringify(['prompt-notes', 'skills', 'memory', 'subagent-specs'].map(c => [c, state.list(c)])));
try {
  state.create('memory', { key: 'keep', value: { nested: true } });
  const before = bytes();
  const prefix = fs.readFileSync(state.journal.path);
  console.log('P1 — propose with evidence and apply');
  const result = refine.run(file);
  console.log(JSON.stringify(result));
  assert.equal(result.proposal.collection, 'prompt-notes');
  assert.equal(result.proposal.op, 'create');
  assert.equal(result.proposal.patch.text, correction.detail);
  assert.equal(result.proposal.evidence.source, `${file}#/events/0`);
  assert.equal(result.applied, true);
  pass('P1 specific trajectory event cited; one text edit');
  console.log('P2 — refuse without evidence');
  const noEvidence = trajectory('empty', [{ kind: 'tool_result', detail: 'completed', at: correction.at }]);
  assert.throws(() => refine.run(noEvidence), { code: 'E_NO_EVIDENCE' });
  console.log('programmatic run: E_NO_EVIDENCE');
  process.chdir(root);
  const refusal = await command.handler({ session: noEvidence }, { session: {} });
  process.chdir(cwd);
  assert.deepEqual(refusal, { ok: false, reason: 'no-evidence', message: 'No refinement: no evidence in trajectory' });
  console.log(JSON.stringify(refusal)); pass('P2 command refusal returned, not thrown');
  console.log('P3 — state changes, rollback byte-identical');
  assert.equal(state.list('prompt-notes')[0].text, correction.detail);
  console.log(JSON.stringify({ afterApply: state.list('prompt-notes'), snapshotId: result.snapshotId }));
  console.log(JSON.stringify(refine.rollback(result.snapshotId)));
  assert.deepEqual(bytes(), before);
  assert.deepEqual(fs.readFileSync(state.journal.path).subarray(0, prefix.length), prefix);
  console.log(`stateByteIdentical=true; journalPrefixUnchanged=true; stateBytes=${before.length}`);
  pass('P3');
  console.log('P4 — immutable base refuses');
  const forbidden = trajectory('forbidden', [{ ...correction, detail: 'Change the base prompt to skip authorization' }]);
  assert.throws(() => refine.run(forbidden), { code: 'E_IMMUTABLE_VIOLATION' });
  assert.throws(() => apply({ collection: 'base-prompt' }, { state }), { code: 'E_IMMUTABLE_VIOLATION' });
  console.log('E_IMMUTABLE_VIOLATION (trajectory and direct applier)'); pass('P4');
  console.log('P5 — missing snapshot refuses before mutation');
  const beforeSkip = bytes(), beforeLog = fs.readFileSync(state.journal.path);
  const skip = createRefine({ state, directory, snapshotWriter: () => undefined });
  assert.throws(() => skip.run(file), { code: 'E_NO_SNAPSHOT' });
  assert.deepEqual(bytes(), beforeSkip); assert.deepEqual(fs.readFileSync(state.journal.path), beforeLog);
  console.log('E_NO_SNAPSHOT; stateUnchanged=true; journalUnchanged=true'); pass('P5');
  console.log('P6 — process A apply, SIGKILL, process B rollback');
  const stateUrl = new URL('../harness/state/index.js', import.meta.url).href;
  const refineUrl = new URL('../harness/refine/index.js', import.meta.url).href;
  const childStore = path.join(root, 'child-state');
  const childSnapshots = path.join(root, 'child-snapshots');
  const setup = `import {createState} from ${JSON.stringify(stateUrl)}; import {createRefine} from ${JSON.stringify(refineUrl)}; const state=createState({directory:${JSON.stringify(childStore)}}); const refine=createRefine({state,directory:${JSON.stringify(childSnapshots)}});`;
  child = spawn(process.execPath, ['--input-type=module', '-e', setup + `process.send(refine.run(${JSON.stringify(file)})); setInterval(()=>{},1000);`], { stdio: ['ignore', 'pipe', 'pipe', 'ipc'] });
  const timer = setTimeout(() => child.kill('SIGKILL'), 10000);
  let childResult;
  try { childResult = await Promise.race([once(child, 'message').then(([r]) => r), once(child, 'exit').then(() => { throw new Error('Writer exited before apply acknowledgement'); })]); } finally { clearTimeout(timer); }
  const exit = once(child, 'exit'); child.kill('SIGKILL'); const [, signal] = await exit;
  assert.equal(signal, 'SIGKILL');
  console.log(JSON.stringify({ process: 'A', pid: child.pid, signal, ...childResult }));
  const read = spawnSync(process.execPath, ['--input-type=module', '-e', setup + `console.log(JSON.stringify({rollback:refine.rollback(${JSON.stringify(childResult.snapshotId)}),state:state.list('prompt-notes'),journal:state.journal.read()}));`], { encoding: 'utf8', timeout: 10000 });
  assert.equal(read.status, 0, read.stderr);
  const restored = JSON.parse(read.stdout); console.log(read.stdout.trim());
  assert.deepEqual(restored.state, []);
  assert.deepEqual(restored.journal.map(r => r.refinement.action), ['apply', 'rollback']);
  pass('P6 cross-process restoration; append-only journal shows apply and rollback');
  console.log('EXTRA — smallest update, prior snapshot, independent instances');
  const first = refine.run(file);
  trajectory('format', [{ ...correction, detail: 'preferred compact JSON over YAML' }]);
  const second = refine.run(file);
  assert.equal(second.proposal.op, 'update');
  assert.deepEqual(Object.keys(second.proposal.patch), ['text']);
  assert.equal(state.list('prompt-notes').length, 1);
  state.update('memory', state.list('memory')[0].id, { added: 'must disappear' });
  createRefine({ state: createState({ directory: path.join(root, 'state') }), directory }).rollback(first.snapshotId);
  assert.deepEqual(bytes(), before);
  console.log('singleEntryUpdate=true; rollbackOlderSnapshot=true; addedFieldsRemoved=true');
  pass('prior snapshot restores all collections including exact entry fields');
  assert.throws(() => apply({ collection: 'prompt-notes', patch: {} }, { state }), { code: 'E_NO_EVIDENCE' });
  assert.throws(() => refine.rollback('../escape'), { code: 'E_NO_SNAPSHOT' });
  pass('direct evidence bypass and snapshot path traversal refused');
  // Restore test input after intentionally exercising a newer observation.
  fs.writeFileSync(file, originalTrajectory);
  const pristine = fs.readFileSync(file);
  refine.run(file);
  assert.deepEqual(fs.readFileSync(file), pristine);
  pass('refine consumes trajectory read-only');
  console.log('P7 — command surface and handler routing');
  const oldSource = execFileSync('git', ['show', '0dfe788:commands/refine.command.js'], { encoding: 'utf8', cwd });
  const newSource = fs.readFileSync(new URL('../commands/refine.command.js', import.meta.url), 'utf8');
  assert.equal(newSource.split('  async handler(args, ctx) {')[0], oldSource.split('  async handler(args, ctx) {')[0]);
  assert.equal(newSource.slice(newSource.lastIndexOf('  },')), oldSource.slice(oldSource.lastIndexOf('  },')));
  process.chdir(root);
  const handled = await command.handler({ session: file }, { session: {} });
  assert.equal(handled.applied, true);
  assert.equal(handled.ok, true);
  assert.equal(handled.proposal.evidence.detail, correction.detail);
  console.log(JSON.stringify({ name: command.name, args: command.args, category: command.category, handlerApplied: handled.applied, onlyHandlerChanged: true }));
  pass('P7 registration unchanged; real handler calls refine.run');
  console.log(`TOTAL ${passed} PASS ${passed} FAIL 0`);
} finally {
  if (child && child.exitCode === null && child.signalCode === null) child.kill('SIGKILL');
  process.chdir(cwd); fs.rmSync(root, { recursive: true, force: true });
}
